### ISSUE TITLE
[cob_teleop] jenkins build error

### ISSUE THREAD

**Issue by floweisshardt** [4am-robotics/cob_command_tools#118]
Jenkins complains about including ScriptAction.h, see http://jenkins.ros.org/job/devel-indigo-cob_command_tools/ARCH_PARAM=amd64,UBUNTU_PARAM=trusty,label=devel/37/console

The jenkins failure is strange....why is including SetLightMode.h possible while including ScriptAction.h fails...where is the difference between cob_light and cob_script_server?

one thing I can see is that in cob_light actionlib is defined as <depend> and in cob_script_server it only is a <exec_depend>...

came up during #117

**Comment by fmessmer** [comment]
fixed in https://github.com/ipa-fmw/cob_command_tools/commit/28c23cd13e5cbade9776b496518facc07cef59f2
