### ISSUE TITLE
[cob_script_server] display (Trigger-)Response within cob_command_gui

### ISSUE THREAD

**Issue by fmessmer** [4am-robotics/cob_command_tools#139]
Currently you do not get any notification if e.g. `init` or `recover` calls fail!

@fmessmer FYI

**Comment by floweisshardt** [comment]
You're right. The result can currently only be seen in the diagnostics window. 
+1 for this feature.

Some time ago we discussed two possibilities:
(i) use colors (red and green) for the buttons to indicate service response or diagnostics.
(ii) show result in text field which currently shows the ROS_MASTER_URI

I vote for (ii) because (i) may lead to confusions if service response and diagnostics show different results. Furthermore there is no 1 to 1 mapping for buttons and diagnostics groups, e.g. behaviour.

**Comment by fmessmer** [comment]
There are two main problems here:

First, the TriggerResponse is currently only used for a [rospy.logerr](https://github.com/ipa320/cob_command_tools/blob/indigo_dev/cob_script_server/src/simple_script_server/simple_script_server.py#L302)...and only if executed with `blocking=True` (which currently not the case for the [`Init all` and `Recover all` buttons](https://github.com/ipa320/cob_command_tools/blob/indigo_dev/cob_command_gui/src/knoeppkes.py#L170-L184))

To solve this, the TriggerResponse (boolean `success` and string `message`) should be passed to the `action_handle` in order to be able to process it in the `cob_command_gui` as the handle is what is [returned](https://github.com/ipa320/cob_command_tools/blob/indigo_dev/cob_script_server/src/simple_script_server/simple_script_server.py#L177-L178)

---

Second - and this is even worse - in [`knoeppkes`](https://github.com/ipa320/cob_command_tools/blob/indigo_dev/cob_command_gui/src/knoeppkes.py#L105) the functions registered to the buttons are executed in a separate thread.

According to the [python API](https://docs.python.org/2/library/thread.html):

> thread.start_new_thread(function, args[, kwargs])
> Start a new thread and return its identifier. The thread executes the function function with the argument list args (which must be a tuple). The optional kwargs argument specifies a dictionary of keyword arguments. When the function returns, the thread silently exits. When the function terminates with an unhandled exception, a stack trace is printed and then the thread exits (but other threads continue to run).

So, I see no chance to option for accessing/evaluating the return value (if we manage to return the required information) of the script server functions from within `knoeppkes`...

**Comment by fmessmer** [comment]
implemented in #141 

![knoeppkes_error_dialog](https://cloud.githubusercontent.com/assets/508006/13548287/ce8ef9a6-e2ec-11e5-971d-e911471f2da1.png)

**Comment by fmessmer** [comment]
Well, it turned out that pop-ups are not the adequate way to display this information.
Thus, it has been removed and only the consistency changes within `cob_script_server` have been merged in #142

**Comment by fmessmer** [comment]
not planned
