### ISSUE TITLE
[cob_teleop] implement the safety mode to move the base

### ISSUE THREAD

**Issue by NadiaHG** [4am-robotics/cob_command_tools#144]
With the joystick should be possible command a direct command (/base/twist_mux/command_teleop_joy) and a safe command using the collision velocity filter (/base/collision_velocity_filter/command). A joystick dead man button can be used to switch the mode .

**Comment by NadiaHG** [comment]
Done! https://github.com/ipa320/cob_command_tools/pull/145

**Comment by mgruhler** [comment]
as #145 has been merged, I'll close this one...
