### ISSUE TITLE
[cob_monitoring] reanimate wifi monitor

### ISSUE THREAD

**Issue by floweisshardt** [4am-robotics/cob_command_tools#203]
@ipa-bnm do you remember the terminal command we used to get the signal quality?

 additionally to the signal quality it would be good to have the MAC of the currently used access point.

**Comment by benmaidel** [comment]
- `iwconfig wlan0 | grep -i quality`
- `cat /proc/net/wireless`

**Comment by benmaidel** [comment]
for the access point:
- `iwconfig wlan0 | grep "Access Point"`

**Comment by fmessmer** [comment]
i would also like to see somerhing generic included with which we could check the connectivity to a specific host+port (e.g. nuance cloud server)
