### ISSUE TITLE
enhance generic throttle

### ISSUE THREAD

**Issue by fmessmer** [4am-robotics/cob_command_tools#210]
follow up of https://github.com/ipa320/msh/issues/727

generic throttle cannot deal with the following properly:
 - local/global_costmap: the rviz display uses a display that visualizes both `costmap` and `costmap_updates` topic
 - image_transport: just subscribing to a compressed image, throttling it and publishing it as `topic_throttled` does not work in `rviz` either...i.e. it cannot have the suffix `_throttled`...this needs to be investigated in more detail

@fmessmer FYI

**Comment by AravindaDP** [comment]
One more feature I like to have is a parameter for repeating last_message in the given rate when no new messages are received. This would allow a topic to have a uniform rate even when source node publishing it in sporadic intervals.

I'm willing to submit this enhancement in a PR if you think it's worthwhile feature

**Comment by fmessmer** [comment]
@AravindaDP 
I don't see an immediate usecase for this - but I'm willing to review/merge a PR that supports your feature as an opt-in

**Comment by fmessmer** [comment]
not planned
