### ISSUE TITLE
[cob_monitoring] no valid Net Data

### ISSUE THREAD

**Issue by HannesBachter** [4am-robotics/cob_command_tools#263]
`No valid NetData` is shown when uptime of PC is less than 5 mins

**Comment by fmessmer** [comment]
which robot?
was the `netdata` service enabled and running?
where you able to access the netdata website on port `http://10.4.XX.PC:19999/`?

**Comment by HannesBachter** [comment]
as far as I remember this was an Issue by `netdata` itself - it only provides information after the PC has been running for more than 5 minutes (so non robot-specific)

**Comment by fmessmer** [comment]
not planned
