### ISSUE TITLE
[cob_script_server] reduce terminal output

### ISSUE THREAD

**Issue by floweisshardt** [4am-robotics/cob_command_tools#279]
currently a `sss.move()` triggers the following terminal output:
```
[WARN] [1582565931.063290]: parameter '/script_server/gripper/default_vel' does not exist on ROS Parameter Server, using default_vel [ 0.1] [rad/sec].
Unknown attribute: type
Unknown attribute: type
Unknown attribute: type
Unknown tag: material
Unknown tag: material
Unknown tag: material
```

`Unknown attribute` and `Unknown tag` were introduces when we added URDF limit checks

**Comment by fmessmer** [comment]
this should be resolved, by loading the URDF once during the `__init__` function and not every `sss.move` command
