### ISSUE TITLE
[noetic][cob_command_gui] fix gtk2 dependency

### ISSUE THREAD

**Issue by fmessmer** [4am-robotics/cob_command_tools#285]
we'll have to decide what to do with this:
`python-gtk2` is no longer available for focal - and there is nothing to easily convert this to

```
E: Unable to locate package python-gtk2
ERROR: the following rosdeps failed to install
  apt: command [apt-get install -y -qq python-gtk2] failed
```

_Originally posted by @fmessmer in https://github.com/ipa320/cob_command_tools/pull/284#discussion_r505285288_

**Comment by fmessmer** [comment]
so far, I did a partial release - ignoring `cob_command_gui`

**Comment by benmaidel** [comment]
Found an easy solution by using the pygtkcompat Compatibility Layer. See: https://pygobject.readthedocs.io/en/latest/guide/porting.html. PR follows
