### ISSUE TITLE
[noetic][cob_monitoring] python3-mechanize is not available for debian:buster

### ISSUE THREAD

**Issue by fmessmer** [4am-robotics/cob_command_tools#289]
```
Could not resolve rosdep key 'python3-mechanize' for distro 'buster':
[python3-mechanize] defined as "not available" for OS version [buster]
	rosdep key : python3-mechanize
	OS name    : debian
	OS version : buster
	Data:
debian:
		  '*':
		  - python3-mechanize
		  buster: null
		fedora:
		- python3-mechanize
		ubuntu:
		  '*':
		  - python3-mechanize
		  bionic: null
		  xenial: null
		
Failed to resolve python3-mechanize on debian:buster with: Error running generator: Failed to resolve rosdep key 'python3-mechanize', aborting.
python3-mechanize is depended on by these packages: ['cob_monitoring']
<== Failed
Some of the dependencies for packages in this repository could not be resolved by rosdep.
<== The following generator action reported that it is missing one or more
    rosdep keys, but that the key exists in other platforms:
'['/usr/bin/git-bloom-generate', '-y', 'rosdebian', '--prefix', 'release/noetic', 'noetic', '-i', '1', '--os-name', 'debian', '--os-not-required']'

If you are absolutely sure that this key is unavailable for the platform in
question, the generator can be skipped and you can proceed with the release.
Skip generator action and continue with release [y/N]?
```

**Comment by fmessmer** [comment]
asked a question on answers.ros.org:  
https://answers.ros.org/question/366881/noetic-build-failed-in-jenkins-debianbuster-could-not-resolve-rosdep-key/

**Comment by fmessmer** [comment]
this resulted in blacklisting `cob_monitoring` - see https://github.com/ros-infrastructure/ros_buildfarm_config/pull/187
this stopped the failure emails for `cob_monitoring`

still I get failure reports for the other `cob_command_tools` packages

**Comment by sloretz** [comment]
```
fatal: Remote branch debian/ros-noetic-cob-script-server_0.6.19-1_buster not found in upstream origin
```

It looks like the job can't find the branch creating the generated Debian Buster package in the release repo for cob_script_server. Maybe `Skip generator action and continue with release [y/N]` causes bloom to skip the Debian Buster dependency completely for all packages in the repo?

@cottsay and @nuclearsandwich, any idea what bloom is doing here ([skip code](https://github.com/ros-infrastructure/bloom/blob/eb447632000cbd2433654463e98332595f8fc181/bloom/commands/git/release.py#L299)), and how it can be worked around?

**Comment by cottsay** [comment]
> how it can be worked around?

The model used in Bloom invokes the generators at a repository level, so an unsatisfied rosdep key in any one package will abort generation for an entire class of OS (i.e. Debian, Ubuntu, Fedora, or RHEL).

My initial impression is that it would be a non-trivial refactor to make the generator "best effort", but it would be possible. We'd have to stop "pre-resolving" the rosdep keys, and we'd need defer returning the special error code used to signal a resolution failure until generation had been attempted on all of the packages. We'd also need to have a policy for what return codes overrule others when multiple packages fail to generate for different reasons.

Barring the refactor in Bloom, the only options I can see are to add all `cobb_command` packages to the exclusion list for Buster, or to split the repository into packages which can be generated successfully, and those that can't along with their downstream dependents.

**Comment by fmessmer** [comment]
@sloretz @cottsay
thanks for the feedback!
these workarounds sound rather complicated...

one idea which I still could try before those workarounds is to switch the dependency from official python(3)-mechanize to python-mechanize-pip instead - allthough I will have to add that rosdep key first...
I will try this within the next days and then come back to you

again: thanks!

**Comment by tfoote** [comment]
@fmessmer Unfortuantely that won't work as a pip rule will be ignored for debian packaging as pip packages are not valid to be added as a dependency of a deb package.

**Comment by fmessmer** [comment]
@tfoote 
ok, so what would happen if I just drop (aka. comment) the dependency?
i.e. it's just a python script that declares the dependency...so it will not result in any build error...but only a runtime exception (crash) in case the dependency is not installed on the executing system
I know that would be ugly, but the script is of minor importance to the `cob_*` toolchain...and I'm rather annoyed of the warnings :eyes: 

or if I still go for the pip dependency, if the pip dependency is ignored by debian packaging, will this only affect debian:buster or also e.g. ubuntu packaging? by declaring the dependency as a pip dependency, the dependency would at least be resolved from source via `rosdep install`, right?

**Comment by sloretz** [comment]
Dropping the dependency sounds like it would work.

Another workaround might be to [point rosdep to a local source.yaml](http://docs.ros.org/en/independent/api/rosdep/html/contributing_rules.html) that has a bogus entry for `python3-mechanize` on Buster, like it says the key resolves to something that's definitely already installed, like`python3-minimal`.

**Comment by fmessmer** [comment]
rosdep key for `python-mechanize-pip` has been proposed in https://github.com/ros/rosdistro/pull/28067

**Comment by tfoote** [comment]
> ok, so what would happen if I just drop (aka. comment) the dependency?

This will be your simplest solution. You can add a check for the import failure and give a nice user message about the missing dependency. 

> or if I still go for the pip dependency, if the pip dependency is ignored by debian packaging, will this only affect debian:buster or also e.g. ubuntu packaging? by declaring the dependency as a pip dependency, the dependency would at least be resolved from source via rosdep install, right?

If you do a pure pip dependency it will fail on all platforms. The debian packaging process ignores the pip resolutions which means it only resolves debian/apt ones. Thus it won't resolve to anything. You can think of the debian packaging pipeline as only seeing apt dependencies anything else in the rosdep database is not seen and will be the equivalent of not being declared. Thus ros/rosdistro#28067 isn't going to help with this at all. And as I commented on it will just conflict with the existing users. To get it to work from source on buster you should just add a buster specific rule using pip for the primary key `python3-mechanize`. 

> Another workaround might be to point rosdep to a local source.yaml that has a bogus entry for python3-mechanize on Buster, like it says the key resolves to something that's definitely already installed, likepython3-minimal.

For this you can always give an empty list `[]` such that it will say it needs nothing to be resolved. 

Shane's approach of manually overriding the local rule would allow you to nullify it on just that platform. But the easier route would be to just remove the declared dependency for all platforms. If you're going to have fallback behaviors for one platform that fallback behavior can work for all of them. So I guess that's my suggestion.

**Comment by fmessmer** [comment]
thanks for your suggestions @tfoote @sloretz 

given the fact that the dependency is only used in a script that does not even have an active appearance in any of the currently supported robots, I'll go with simply dropping the dependency :point_right: #295 
(its only appearance is commented in the launch file of an inactive robot - see #295)

I'll trigger a fresh release....and then, `cob_monitoring` does no longer  need to be ignored on the buildfarm anymore...

**Comment by fmessmer** [comment]
having removed the dependency and re-releasing `cob_command_tools`, blacklisting `cob_monitoring` should no longer be needed: https://github.com/ros-infrastructure/ros_buildfarm_config/pull/196

**Comment by fmessmer** [comment]
everything seems fine now
