### ISSUE TITLE
rework teleop to support cob4 and use ps3 joystick

### ISSUE THREAD

**Issue by floweisshardt** [4am-robotics/cob_command_tools#92]
- same button mapping for logitech and sony
- unify v1 and v2
- no global namespace remapping
- un-bride-ify
- catkin_linit

maybe use python and sss?

**Comment by floweisshardt** [comment]
@ipa-nhg please have a look at http://wiki.ros.org/joy_teleop if we can reuse some of this.

seems to be a generic implementation to map any action to joystick buttons. Configuration see https://github.com/ros-teleop/teleop_tools/blob/indigo-devel/joy_teleop/config/joy_teleop.yaml.

**Comment by fmessmer** [comment]
@ipa-nhg is on it: https://github.com/ipa-nhg/cob_command_tools/tree/new_teleop_node

**Comment by NadiaHG** [comment]
Already done, tested and merged.
