### ISSUE TITLE
teleop_v1 doesn't work with new ros_canopen controllers on indigo

### ISSUE THREAD

**Issue by jobstvogt** [4am-robotics/cob_command_tools#93]
We can't use teleop on our cob3-8 with the logitech joypad at the moment. Should we try using teleop_v2?

**Comment by floweisshardt** [comment]
This is a namespace problem. please use _v1 and add a remap to the new namespace in the teleop launch file in cob_bringup.

**Comment by jobstvogt** [comment]
But I think the "/component_controller/command_vel" topic of type "brics_actuator::JointVelocities" that is published by teleop_v1 doesn't exist in the new controller design or am I wrong?

**Comment by floweisshardt** [comment]
I thought you were talking about the base. 

You're right, there is no more joystick control for the arms. In case you'd like to use something for fast teach-in I can recommend rqt with the joint_trajectory_controller plugin.

**Comment by fmessmer** [comment]
Well, the publishers for brics_actuator message (command_vel) are still in the code.
Thus, I guess it is a namespace problem for components other than the base as well!
We introduced parameters that help us with handling this kind of things, maybe we just missed something in the cob3-8 yamls?

@jobstvogt 
Are you referring to a component in particular?
What code version are you using? Hydro/Indigo? Releases or Source?
If you provide us with more details, we might be able to help.

---

As a side note, the joint_trajectory_controller plugin is only applicable for components using the JointTrajectoryController from ros_controllers...and I guess, cob3-8 does not use those but the cob_trajectory_controller instead

**Comment by jobstvogt** [comment]
I updated the robot to Indigo 3 or 4 weeks ago. I had problems getting the new ros_canopen stuff to work. At the beginning it was not possible to init the schunk actuators. For that reason i changed everything back to the deprecated ipa_canopen implementation. It was some work to change all the namespaces and topics but it works in the end. And last week i gave the ros_canopen implementation (source version) a second try and it is running now but i want to control the arm, torso and tray with the joystick. The rqt_plugin is working but it's not a good replacement for the joystick. What are the advantages of ros_canopen to the old ipa_canopen?

Another question: Have you tried the cob_twist_controller or cartesian_controller on a cob3? 

P.S.: You have to edit the Indigo installation manual. The peak can driver installation isn't correct explained for the new socketcan interface.

**Comment by floweisshardt** [comment]
solved
